### ISSUE TITLE
NullPointerException - Doom Energy Mine Mastery

### ISSUE THREAD

**Issue by brettg94** [qcwxezda/Starsector-Ship-Mastery-System#1]
Hi; looks like the energy mine mastery effect can cause a crash in combat. Here's the relevant stack trace from the log:

```
ERROR com.fs.starfarer.combat.CombatMain  - java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "shipmastery.util.EngineUtils.getBaseShip(com.fs.starfarer.api.combat.ShipAPI)" is null
java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because the return value of "shipmastery.util.EngineUtils.getBaseShip(com.fs.starfarer.api.combat.ShipAPI)" is null
	at shipmastery.util.CollisionUtils.canCollide(CollisionUtils.java:106)
	at shipmastery.mastery.impl.combat.shipsystems.EnergyMineConversion$EnergyMineExplosionScript.onExplosion(EnergyMineConversion.java:125)
	at com.fs.starfarer.combat.ai.GuidedProximityFuseAI.explode(Unknown Source)
	at com.fs.starfarer.combat.ai.GuidedProximityFuseAI.advance(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advanceInner(Unknown Source)
	at com.fs.starfarer.combat.CombatEngine.advance(Unknown Source)
...
```

Looks like `EnergyMineExplosionScript.onExplosion()` is the trigger. The underlying cause seems to be that `CollisionUtils.canCollide()` can't handle a possible `null` value returned from `EngineUtils.getBaseShip()`.

```
// Always ignore source and source modules
if (entity instanceof ShipAPI && EngineUtils.getBaseShip((ShipAPI) entity).equals(EngineUtils.getBaseShip(source))) return false;
```
I don't think `EngineUtils.getBaseShip` is getting passed a `null` argument, since it's validated as an instance of ShipAPI beforehand (is that right? Not too familiar with Java.). I dug around a bit but didn't find any obvious missed edge cases. Let me know if I can provide any more insight. Thank you!

**Comment by qcwxezda** [comment]
Should be fixed in 0.10, thanks for the report
